=== AnnAiko/parser/tariffSchema.xsd
<?xml version="1.0"?>

<schema version="1.0"
           xmlns="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified"
           targetNamespace="http://www.example.com/tariffs"
           xmlns:tns="http://www.example.com/tariffs">
    <element name="tariffs">
        <complexType>
            <sequence>
                <element name="tariff"
                         type="tns:Tariff"
                         minOccurs="1"
                         maxOccurs="unbounded" />
            </sequence>
        </complexType>
    </element>
    <complexType name="Tariff">
        <sequence>
            <element name="name" type="string" />
            <element name="payroll" type="integer" />
            <element name="callprices" type="tns:Callprices"/>
            <element name="SMSprice" type="float" />
            <element name="parameters" type="tns:Parameters" />
        </sequence>
        <attribute name="id" type="integer" /> 
        <attribute name="operator" use="optional" default="Tele2" >
            <simpleType>
                <restriction base="string">
                    <enumeration value="Tele2"></enumeration>
                    <enumeration value="МТС"></enumeration>
                    <enumeration value="Билайн"></enumeration>
                    <enumeration value="Мегафон"></enumeration>
                </restriction>
            </simpleType>
        </attribute>
    </complexType>
    <complexType name="Callprices">
        <sequence>
            <element name="inside" type="float" />
            <element name="outside" type="float" />
            <element name="stationaryphone" type="float" />
        </sequence>
    </complexType>
    <complexType name="Parameters">
        <sequence>
            <element name="likephone" type="integer" />
            <element name="tariffing" type="string" />
            <element name="connection" type="integer" />
        </sequence>
    </complexType>
</schema>

=== AnnAiko/parser/Задание_4_SAX/Разбор XML/tariffDocument.xml
<?xml version="1.0" encoding="UTF-8"?>

<tariffs
    xmlns:xsi='http://www.w3.org/2001/XMLSchema-instance'
    xmlns='http://www.example.com/tariffs'
    xsi:schemaLocation='http://www.example.com/tariffs tariffSchema.xsd'
    >  
    
    <tariff id="1" operator="Tele2">
        <name>2Plus</name>
        <payroll>220</payroll>
        <callprices>
            <inside>0.9</inside>
            <outside>2.4</outside>
            <stationaryphone>2.0</stationaryphone>
        </callprices>
        <SMSprice>0.96</SMSprice> 
        <parameters>
            <likephone>2</likephone>
            <tariffing>поминутная</tariffing>
            <connection>0</connection>
        </parameters>
    </tariff>
    <tariff id="2" operator="МТС">
        <name>Тарифище</name>
        <payroll>585</payroll>
        <callprices>
            <inside>1.5</inside>
            <outside>3.0</outside>
            <stationaryphone>2.6</stationaryphone>
        </callprices>
        <SMSprice>2</SMSprice>
        <parameters>
            <likephone>0</likephone>
            <tariffing>12-секундная</tariffing>
            <connection>30</connection>
        </parameters>
    </tariff>
</tariffs>
